remote_theme: pages-themes/minimal@v0.2.0
plugins:
title: Chandni Raja
logo: /files/img/chands3.png    
description: PhD Candidate in Economics
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false

