remote_theme: pages-themes/minimal@v0.2.0
plugins:
title: Chandni Raja
logo: /assets/img/chands.png
description: PhD Candidate in Economics, UCLA
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
