remote_theme: pages-themes/minimal@v0.2.0
plugins:
title: Chandni Raja
logo: /assets/img/chands3.png
description:     
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github:
  is_project_page: false
