relativeURLs = true
title = "Chandni Raja"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "me hej hej"
    logo = "chands.jpg" 
    
